version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -v
      - mvn compile
      - mvn test -P sample-test
artifacts:
  files:
    - ./**/*  
